In [63]:
import numpy as np
import pandas as pd
import sklearn.preprocessing as preprocessing
import matplotlib.pyplot as plt

In [65]:
fords=pd.read_csv('fords.csv')
fords = fords[['Year','Mileage','Price','Age']]
scaler = preprocessing.normalize(fords)
print(scaler.scale_)

[2.00488661e+03 5.60155714e+04 2.53135326e+04 4.28031496e+00]


In [36]:
enc = preprocessing.OrdinalEncoder()
X = [['male', 'from US', 'uses Safari'], ['female', 'from Europe', 'uses Firefox']]
enc.fit(X)
print(enc.transform([['male', 'from US', 'uses Firefox']]))

[[1. 1. 0.]]


In [44]:
enc = preprocessing.OneHotEncoder()
X = [['male', 'from US', 'uses Safari'], ['female', 'from Europe', 'uses Firefox']]
enc.fit(X)

print(enc.transform([['female', 'from US', 'uses Safari'],
               ['male', 'from Europe', 'uses Safari']]).toarray())

[[1. 0. 0. 1. 0. 1.]
 [0. 1. 1. 0. 0. 1.]]


In [46]:
X

[['male', 'from US', 'uses Safari'], ['female', 'from Europe', 'uses Firefox']]

In [48]:
df = pd.DataFrame({'sex': ['male','female'], 'country': ['from US','from Europe'],
                 'browser': ['uses Safari','Uses Firefox'], 'numerical': [1, 2]})
df.head()

sex      country       browser  numerical
0    male      from US   uses Safari          1
1  female  from Europe  Uses Firefox          2

In [49]:
pd.get_dummies(df)

numerical  sex_female  sex_male  country_from Europe  country_from US  \
0          1           0         1                    0                1   
1          2           1         0                    1                0   

   browser_Uses Firefox  browser_uses Safari  
0                     0                    1  
1                     1                    0

In [60]:
X = np.array([[ -3., 5., 15 ],
              [  0., 6., 14 ],
              [  6., 3., 11 ]])
est = preprocessing.KBinsDiscretizer(n_bins=[3, 2, 2], encode='ordinal').fit(X)
print(est.transform(X))

[[0. 1. 1.]
 [1. 1. 1.]
 [2. 0. 0.]]


In [62]:
X = [[ 1., -1.,  2.],
     [ 2.,  0.,  0.],
     [ 0.,  1., -1.]]
binarizer = preprocessing.Binarizer()
print(binarizer.transform(X))

[[1. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
